### ISSUE TITLE
memory leak/GC issues?

### ISSUE THREAD

**Issue by gasparch** [davisp/jiffy#130] opened 2016-09-27 07:27 UTC
When using jiffy under constant load (20-50mb initial JSON files and then about 100kb/sec decoded) I can see total memory usage and binary memory usage going it.

GC occurs from time to time, but still never cleans all binary memory. 

When using Poison instead of jiffy I can see all binary memory being freed up after decoding.

**Comment by davisp** [comment] 2016-09-28 17:14
@gasparch Huh. My guess is that's because Jiffy returns subbinaries for strings that don't have escaped characters. Ie, Given <<"{\"foo\":true}">>, decoding that returns {[{<<"foo">>, true}]}, where <<"foo">> is a subbinary of the original input, thus keeping the whole input around. A quick test you could try to validate this would be something like:

```erlang
deref({Props}) when is_list(Props) ->
    {deref_obj(Props)};
deref(Elems) when is_list(Elems) ->
    deref_arr(Elems);
deref(Bin) when is_binary(Bin) ->
    binary:copy(Bin);
deref(Else) ->
    Else.

deref_obj([]) ->
    [];
deref_obj([{Key, Val} | RestProps]) ->
    [{dref(Key), deref(Val)} | dref_obj(RestProps)].

deref_arr([]) ->
    [];
deref_array([Elem | RestElems]) ->
    [deref(Elem) | deref(RestElems)].

mydecode(Input) ->
    deref(jiffy:decode(Input)).
```

**Comment by vans163** [comment] 2016-12-15 19:48
@davisp  I just ran into this. This is definitely happening in the NIF

```erlang
do_leak() ->
    AllA = binary:copy(<<"B">>, 9*1000*1000),
    Json = <<"{\"key\": \"", AllA/binary,"\"}">>,
    jiffy:decode(Json, [return_maps]).
```

It only happens with large input.

**Comment by davisp** [comment] 2016-12-15 21:13
@vans163 What version of Jiffy? How are you measuring memory usage?

This script seems to allocate 25M and then frees it after the 2s are up. That's based by watching beam.smp in top while I run the script.

```erlang
DoLeak = fun() ->
    AllA = binary:copy(<<"A">>, 25 * 1000 * 1000),
    Json = <<"{\"key\":\"", AllA/binary, "\"}">>,
    jiffy:decode(Json, [return_maps])
end,

spawn(fun() -> DoLeak(), timer:sleep(2000) end).
```

**Comment by davisp** [comment] 2016-12-15 21:14
Also, what version of Erlang?

**Comment by vans163** [comment] 2016-12-16 01:30
@davisp This commit a7db72493d228853 so latest master.

R19.1 and R19 I tested on.  

Yea this is strange. If you spawn a process, there is no leak.  But if you do it in the shell then crash/gc the shell, it leaks.

Basically I have an app that fetches 9mb jsons, it crashes and goes OOM it took me quite some time to pinpoint what was wrong, I even added a patch to jiffy to binary:copy every term from the returned map to a new map, to make sure no refs were held to a large bin by accident. 

In that app I am doing the decoding in a throwaway process that dies right after decode.

 Switching to JSX instead of jiffy makes the problem go away.  Using 'instrument' I can see the held binary is the raw json text that is passed to the jiffy:decode/2 function.

**Comment by gasparch** [comment] 2016-12-16 09:48
I'll also try to write (unit) tests in my app to make sure we don't have that problem. Will report back when done. 

Actually running program with following options made things much better (binaries do not get stuck that much in multiblock carriers).  Read [this](https://blog.heroku.com/logplex-down-the-rabbit-hole) and [this](http://erlang.org/doc/man/erts_alloc.html) for more details.

```sh
iex --erl "+MBas aobf +MBlmbcs 1024 +MBsbct 256 +MBsmbcs 128 +MBramv true" 
```

**Comment by davisp** [comment] 2016-12-16 16:09
@vans163 You're probably just seeing the shell server holding onto a ref in its history. If you just do `exit(self(), kill)` the server just spawns another shell process but the shell server remains. This process holds all of the data that lets you run `h()`, `v(N)`, etc. You can try the snippet below to kill the shell server directly which reclaims the data:

```erlang
{links, Links} = process_info(self(), links),
[exit(P, kill) || P <- Links].
```

Also, when you fetch the JSON, is that through a different process? Remember that binaries aren't collected until every process that ever touched it is garbage collected. I've heard of cases where a low volume server process distributing large binaries would hold on to references for a long time since it wasn't doing much work for each binary. An easy hacky patch is to just hibernate any such processes often.

@gasparch Sounds good, and thanks for the pointers to the carrier info. I've read on them a bit but never needed to tweak them directly in any of my apps.

**Comment by vans163** [comment] 2016-12-16 16:34
@davisp I was thinking that would be the case, but in the case of ETS tables killing the shell process using exit/2 seems to release everything.

And yes I checked when fetching the JSON to ensure nothing would be holding a ref, I even write my own lib to do the get request vs relying on a 3rd party lib that spawns a supervisor tree just to do a simple HTTP get request.

Basically swapping JSX in for jiffy fixed all issues without touching anything else. The app has been running for over 24 hours now and its memory usage has not budged binaries were 6mb, and they are still 6mb.  With jiffy the app would probably be at 200-400mb binary usage by now.

**Comment by davisp** [comment] 2017-01-31 18:25
Strange. Seems like JSX has fixed it for you though. I'll close this but if anyone sees anything similar feel free to reopen and add any observations.

**Comment by ericmj** [comment] 2017-11-01 10:32
We have the same issue. Would there be interest in an option that calls `binary:copy/1` on all decoded binaries?

**Comment by gasparch** [comment] 2017-11-01 13:28
Without explaining magic here, could you run it with following options:

```
ERL_OPTIONS=--erl "+MBas aobf +MBlmbcs 1024 +MBsbct 256 +MBsmbcs 128 +MBramv true"
iex ${ERL_OPTIONS} -S mix
```

and see if it fixes memory leak for you.

**Comment by ericmj** [comment] 2017-11-01 14:38
@gasparch Binary memory usage seems to be roughly the same with these options.

**Comment by gasparch** [comment] 2017-11-01 14:45
You mean it still leaks? Did you tried calling garbage_collect manually on parsing process?

**Comment by ericmj** [comment] 2017-11-01 14:48
It's not really a leak, but we use a lot more binary memory (~10x more) when we switched to jiffy and it takes a long time for the memory to be reclaimed. Garbage collecting all processes only very slightly reduces memory usage, probably because we are still referencing the source json.

**Comment by gasparch** [comment] 2017-11-01 15:51
Actual problem may be that while memory is still freed (and GC does it work), memory allocator keeps half-empty carriers around. Memory fragmentation is a biggest evil in this case ;)

**Comment by davisp** [comment] 2017-11-01 18:42
@ericmj Have you tried something similar to the functions at [1]? I'm not against adding the option but I'd prefer to be fairly certain its just the references and not something else like half-empty carriers as @gasparch mentions.

[1] https://github.com/davisp/jiffy/issues/130#issuecomment-250233509

**Comment by ericmj** [comment] 2017-11-01 18:48
@davisp Yes, that's the workaround we currently have in production. Doing explicit binary copies on the values returned by jiffy decode gets us back to the same binary memory usage we had before switching to jiffy.

Unfortunately this requires reallocating the entire structure returned by jiffy so making the copies inside jiffy should be more efficient. The measurements I did indicate that doing the explicit binary copies after jiffy decode almost doubles the decode time for us. I have not yet measured making the copies inside jiffy.

**Comment by davisp** [comment] 2017-11-01 19:21
@ericmj Give this a branch [1] a try and see how it works for you. I've only *very* lightly tested it and have done zero performance analysis on it.

[1] https://github.com/davisp/jiffy/tree/copy-strings

**Comment by ericmj** [comment] 2017-11-03 11:27
@davisp I tried your branch and I get a segfault when using `copy_strings`. I can provide you with the JSON that produces the segfault privately if you want it.

**Comment by davisp** [comment] 2017-11-03 15:19
@ericmj Please do! You can send it to the email address on my github profile.

**Comment by davisp** [comment] 2017-11-05 21:36
@ericmj Thanks for the reproducer! I've pushed a minor patch to the copy-strings branch that should fix things. Can you give that a whirl and see how your large decoding performs with it?

**Comment by ericmj** [comment] 2017-11-05 22:29
Will do, thanks for the quick fix.

**Comment by ericmj** [comment] 2017-11-06 15:28
@davisp The fix is working. With your branch we do not see any increased binary memory usage and we actually do not notice any increase in decode time when copying strings. Thank you!

**Comment by ericmj** [comment] 2017-12-15 11:15
@davisp Can you push the latest releases to Hex also?

**Comment by MikeBenza** [comment] 2018-02-26 11:51
It looks like the copy-strings branch is no longer available.  What's the status on this?  I'm also seeing very large binary memory accumulations that we can't clear with a GC.

**Comment by aknrdureegaesr** [comment] 2018-03-14 11:07
According to the [README.md](https://github.com/davisp/jiffy/blob/master/README.md), the `copy_strings` options has been made available. So the issue can be closed?

**Comment by davisp** [comment] 2018-03-14 15:31
Closing. If anyone has different memory issues feel free to open a new issue.

**Closed by davisp** 2018-03-14 15:31 UTC
